[package]
name = "asdf"
version = "0.1.0"
authors = ["ben blum <bblum0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
float-cmp = "0.6.0"
streaming-stats = "0.2.3"
