[package]
name = "read-jmdict"
version = "0.1.0"
authors = ["ben blum <bblum0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs= "0.8"
kanji = "1.1.0"

[[bin]]
name = "read-jmdict"
path = "main.rs"
